Env: debug
Secret: 66d2e42661bc292f8237b4736a423a36
JWTSecret: F2NFhljyALXM86x

Sync:
  #  GRPC
  #  REDIS
  #  ETCD
  #  AMQP
  Target: REDIS
  Grpc:
    Addr: 192.167.167.167:9527
  Redis:
    Addrs: [ "192.167.167.167:6379" ]
    User: ""
    Pass: ""
    MasterName: ""
    DB: 0


Issuer:
  Name: issuer-api
  Host: 0.0.0.0
  Port: 9090

  DevServer:
    Enabled: true

  User:
    Name: anson@test.com
    Pass: "000000"

  Mysql:
    Dns: root:123456@tcp(127.0.0.1:3306)/cert-gateway?charset=utf8mb4&parseTime=true
    Migration:
      Path: "internal/database/migration"
      Db: "cert-gateway"




Gateway:
  IssuerAddr: k8s cert service
