Secret: 66d2e42661bc292f8237b4736a423a36
JWTSecret: F2NFhljyALXM86x

Logger:
  Level: debug    # [debug,info,error,severe]
  Mode: console   #  default=console,options=[console,file,volume]
  Path: logs      # represents the log file path
  KeepDays: 0     # default 0
  MaxSize: 0      # default 0

Sync:
  #  GRPC
  #  REDIS
  #  ETCD
  #  AMQP
  Target: GRPC
  GrpcServer:
    Port: 9527
  GrpcClient:
    Listen: 0.0.0.0:9527 # grpc server addr
  Redis:
    Addrs: [ "192.167.167.167:6379" ]
    User: ""
    Pass: ""
    MasterName: ""
    DB: 0


Issuer:
  Name: issuer-api
  Host: 0.0.0.0
  Port: 9090
  Timeout: 20000

  CheckExpireWithCron:
    # Redis
    # Cron
    Type: "Cron"
    Cron: "*/1 * * * *"

  DevServer:
    Enabled: true
    Port: 6060

  CADirURL: "https://acme-staging-v02.api.letsencrypt.org/directory" # letsencrypt staging
  #  CADirURL: "https://acme-v02.api.letsencrypt.org/directory" # letsencrypt prd

  User:
    Name: anson@test.com
    Pass: "000000"

  Mysql:
    User: root
    Pass: "123456"
    Host: 127.0.0.1
    Port: "3306"
    DB: issuer-gateway


Gateway:
  # 证书申请服务
  IssuerService: http://127.0.0.1

