Secret: 66d2e42661bc292f8237b4736a423a36
IssuerAddr: k8s cert service

Sync:
  # GRPC
  # REDIS
  # ETCD
  # AMQP
  #  redisUrl: redis://localhost:6379?db=3&password=
  Type: REDIS
#  Address: 127.0.0.1:9527
  Address: 127.0.0.1:6379
  User: ""
  Pass: ""

