Mysql:
  Dns: "root:123456@tcp(192.167.167.167:3306)/cert-gateway?charset=utf8mb4&parseTime=true"
  Migration:
    Path: "/Users/gzf/cert-gateway/cert/init/database/migration"
    Database: "cert-gateway"

Env: debug

Acme:
  Email: nsgzfei@gmail.com
